# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_experiment_model_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emodel',
            old_name='alrorithm',
            new_name='algorithm',
        ),
    ]
