# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_dataset_column_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='colcount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='rowcount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
