# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_auto_20170727_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='emodel',
            name='status',
            field=models.CharField(default='Initiated', max_length=50),
        ),
    ]
