# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0004_emodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='f1_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='total_time_spent',
            field=models.FloatField(default=0),
        ),
    ]
